# Generated by Django 4.0.1 on 2022-01-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_pat', models.CharField(max_length=100)),
                ('fun_fact', models.TextField(max_length=250)),
                ('lifespan', models.IntegerField()),
            ],
        ),
    ]
