# Generated by Django 4.0.1 on 2022-01-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=100)),
                ('habitat', models.TextField(max_length=250)),
                ('frog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.frog')),
            ],
        ),
    ]
